#!/usr/bin/python
# -*- mode: python -*-

# Copyright 2014 Sebastian Jordan

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


import argparse
from gitlabhookcatcher.taghook import (TagHookHandler,
                                       run_server)

if __name__ == '__main__':
    parser = argparse.ArgumentParser(\
        description="Start a webhook "
                    "catcher for handling 'tag push' events")
    parser.add_argument(
        '--port', 
        type=int,
        required=True,
        help='The port where the hook catcher will listen for post '
             'requests')
    parser.add_argument(
        '--repository',
        required=True,
        help='The name of the repository to send the distribution to')
    parser.add_argument(
        '--allowed',
        required=False,
        nargs='*',
        help='A list of IP addresses, that are allowed to push events')
    args = parser.parse_args()
    TagHookHandler.allowedHosts=args.allowed
    TagHookHandler.pypirepo=args.repository
    run_server(port=args.port)

