#!/usr/bin/env python

# Copyright 2014 Sebastian Jordan

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

"""Upload all the tags of a git repository as new releases to pypi
server"""

import argparse
import subprocess
import os.path

from gitlabhookcatcher.util import tempDir

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--repository",
        required=True,
        help="Repository where tags should be "\
             "uploaded from.  This must be an absolute path.")
    parser.add_argument(
        "--pypi",
        required=True,
        help="Name of the pypi repository.  This name should "\
             "appear in your .pypirc")
    parser.add_argument(
        '--python-path',
        required=False,
        help='The path to the python interpreter that will be '
             'used to create the source distribution')
    args = parser.parse_args()
    
    python_p = args.python_path
    if python_p is None:
        python_p = "python"
    with tempDir():
        makeTagReleases(repo= args.repository, 
                        pypi = args.pypi,
                        python_path = args.python_path)


def makeTagReleases(repo, pypi, python_path="python"):
    """Clone a repository and upload tags to pypi

    This code assumes that the cwd (current working directory) is the
    git repository in question.
    """

    # clone repository
    clone_proc = subprocess.Popen(['git','clone',repo,'.'])
    clone_proc.communicate()
    if clone_proc.returncode != 0:
        raise Exception("Cannot clone repository \"%s\"" % repo)

    # get tags
    tag_proc = subprocess.Popen(['git','tag'],stdout=subprocess.PIPE)
    (tags, err) = tag_proc.communicate()

    # make releases
    for tag in tags.split():
        subprocess.call(['git','checkout',tag,'-f'])
        if os.path.exists("setup.py"):
            subprocess.call([python_path,
                             "setup.py",
                             "sdist",
                             "upload",
                             "-r",
                             pypi])


if __name__ == '__main__':
    main()
